root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/api"
  bin = "./tmp/main"
  full_bin = ""
  args_bin = []
  exclude_patterns = ["*/tmp/*"]
  include_patterns = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_ext = ["so", "o", "a", "dll", "dylib", "exe", "exe~", "class", "jar", "zip", "out", "rbc", "o", "object"]
  include_dir = []
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_files = []
  exclude_files = ["*.txt"]
  delay = 1000
  stop_on_error = true
  log = "build-errors.log"
  send_interrupt = false
  kill_delay = 0

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  running = "green"
