@baseUrl = http://localhost:3001

### Health Check
GET {{baseUrl}}/health

### Register New User
POST {{baseUrl}}/auth/register

{
  "email": "user@example.com",
  "password": "password123",
  "name": "Joe Mama"
}

### Login User
POST {{baseUrl}}/auth/login

{
  "email": "h@h.com",
  "password": "hhhhhh"
}

### Logout
POST {{baseUrl}}/auth/logout

### Get Cart
GET {{baseUrl}}/cart

### Set Cart
POST {{baseUrl}}/cart

{
  "cartItems": [
    {
      "productId": 2,
      "quantity": 2
    }
  ]
}
