@baseUrl = http://localhost:3001
@contentType = application/json

### Health Check
GET {{baseUrl}}/health

### Register New User
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "user@example.com",
  "password": "password123",
  "name": "Joe Mama"
}

### Login User
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "user@example.com",
  "password": "password123"
}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}

### Cart
GET {{baseUrl}}/cart

